routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

/*Route::get('/','PagesController@getIndex');
Route::get('/about', 'PagesController@getAbout');
Route::get('/contact','PagesController@getContact');
Route::resource('posts','PostController');*/


Route::group(['middleware' => ['web']], function () {
    Route::get('blog/{slug}',['as'=>'blog.single','uses'=>'BlogController@getSingle'])->where('slug','[\w\d\-\_]+');
    Route::get('blog',['as'=>'blog.index','uses'=>'BlogController@getIndex']);

    Route::get('contact', 'PagesController@getContact');
    Route::post('contact', 'PagesController@postContact');
    Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
    Route::get('about', 'PagesController@getAbout');
    Route::get('/', 'PagesController@getIndex');
    Route::resource('posts', 'PostController');
    // Categories
    Route::resource('categories', 'CategoryController', ['except' => ['create']]);
    Route::resource('tags', 'TagController', ['except' => ['create']]);

    // Comments
    Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
    Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);
    Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);
    Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);
    Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);

});

Auth::routes();

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function category(){
                return $this->belongsTo('App\Category');
    }
    public function tags(){
              return $this->belongsToMany('App\Tag');

    }
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

}

resources/views/posts/create.blade.php
@extends('main')


@section('title','|Create New Post')
@section('stylesheets')
    {!! Html::style('css/select2.min.css') !!}
    {!! Html::style('css/parsley.css') !!}
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
    @endsection
@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            <h1> Create New Post</h1>
            <hr>
            {!! Form::open(array('route' => 'posts.store', 'data-parsley-validate' => '', 'files' => true)) !!}
            {{ Form::label('title','Title:') }}
            {{Form::text('title',null,array('class'=>'form-control','required'=>''))}}
            {{ Form::label('slug','Slug:') }}
            {{Form::text('slug',null,array('class'=>'form-control','required'=>'','minlength'=>'5','maxlength'=>'255'))}}
            {{ Form::label('category_id','Category:') }}
            <select class="form-control" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach


            </select>
            {{ Form::label('tags', 'Tags:') }}
            <select class="form-control select2-multi" name="tags[]" multiple="multiple">
                @foreach($tags as $tag)
                    <option value='{{ $tag->id }}'>{{ $tag->name }}</option>
                @endforeach

            </select>

            {{ Form::label('featured_img', 'Upload a Featured Image') }}
            {{ Form::file('featured_img') }}


            {{ Form::label('body','Post Body:') }}
            {{Form::textarea('body',null,array('class'=>'form-control'))}}
            {{Form::submit('Create Post',array('class'=>'btn btn-success btn-lg btn-block','style'=>'margin-top:20px;'))}}
            {!! Form::close() !!}
        </div>



    </div>
@endsection
@section('scripts')
    {!! Html::script('js/parsley.min.js')!!}
    {!! Html::script('js/select2.min.js') !!}
    <script type="text/javascript">
        $('.select2-multi').select2();
    </script>

@endsection

resources/views/posts/edit.blade.php
@extends('main')


@section('title','|Edit Blog Post')
@section('stylesheets')
    {!! Html::style('css/select2.min.css') !!}
    {!! Html::style('css/parsley.css') !!}
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@endsection
@section('content')
    <div class="row">
        {!! Form::model($post,['data-parsley-validate'=>'','route' => ['posts.update',$post->id],'method'=>'PUT']) !!}
        <div class="col-md-8">
            {{ Form::label('title','Title:') }}
            {{Form::text('title',null,array('class'=>'form-control input-lg','required'=>''))}}
            {{ Form::label('slug','Slug:',['class'=>'form-spacing-top']) }}
            {{Form::text('slug',null,array('class'=>'form-control input-lg','required'=>''))}}
            {{ Form::label('category_id','Category:',['class'=>'form-spacing-top']) }}
            {{Form::select('category_id',$categories,null,array('class'=>'form-control'))}}
            {{ Form::label('tags', 'Tags:', ['class' => 'form-spacing-top']) }}
            {{ Form::select('tags[]', $tags, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple']) }}
            {{ Form::label('body','Post Body:',['class'=>'form-spacing-top']) }}
            {{Form::textarea('body',null,array('class'=>'form-control','required'=>'','maxlength'=>'255'))}}
        </div>
        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Create At:</dt>
                    <dd>{{ date('M j, Y h:ia',strtotime($post->created_at))}}</dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Updated At:</dt>
                    <dd>{{ date('M j, Y h:ia',strtotime($post->updated_at))}}</dd>
                </dl>
                <hr>
                <div class="row">

                    <div class="col-sm-6">
                        {{Html::linkRoute('posts.show','Cancel',array($post->id),array('class'=>"btn btn-danger btn-block"))}}

                    </div>
                    <div class="col-sm-6">
                        {{Form::submit('Save changes',array('class'=>'btn btn-success btn-block'))}}


                    </div>

                </div>
            </div>


        </div>

{!! Form::close() !!}

    </div>
@endsection
@section('scripts')
    {!! Html::script('js/parsley.min.js')!!}
    {!! Html::script('js/select2.min.js') !!}
    <script type="text/javascript">
        $('.select2-multi').select2();
        $('.select2-multi').select2().val({!! json_encode($post->tags()->getRelatedIds()) !!}).trigger('change');

    </script>


@endsection

resources/views/posts/index.blade.php
@extends('main')


@section('title','|All Posts')
@section('content')
    <div class="row">
    <div class="col-md-10">
        <h1> All Posts</h1>
    </div>
    <div class="col-md-2">
           <a href="{{route('posts.create')}}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Create new Post</a>
    </div>

        <div class="col-md-12">
            <hr>
        </div>
</div>
    <div class="row">
        <table class="table">
            <thead>
            <th>#</th>
            <th>Title</th>
            <th>Body</th>
            <th>Created at</th>
            <th></th>

            </thead>
            <tbody>
             @foreach($posts as $post )
                 <tr>
                     <th>{{$post->id}}</th>
                     <th>{{$post->title}}</th>
                     <th>{{substr(strip_tags($post->body),0,50)}}{{strlen(strip_tags($post->body))>50?"...":""}}</th>
                     <th>{{ date('M j, Y h:ia',strtotime($post->created_at))}}</th>
                     <th><a href="{{route('posts.show',$post->id)}}" class="btn btn-default btn-sm">view</a>
                         <a href="{{route('posts.edit',$post->id)}}" class="btn btn-default btn-sm">Edit</a></th>
                 </tr>
                 @endforeach
            </tbody>
        </table>
        <div class="text-center">

            {!! $posts->links() !!}
        </div>
    </div>

@stop

resources/views/posts/show.blade.php
@extends('main')

@section('title', '| View Post')

@section('content')

    <div class="row">
        <div class="col-md-8">
            <h1>{{ $post->title }}</h1>

            <p class="lead">{!!  $post->body !!}</p>

            <hr>

            <div class="tags">
                @foreach ($post->tags as $tag)
                    <span class="label label-default">{{ $tag->name }}</span>
                @endforeach
            </div>

            <div id="backend-comments" style="margin-top: 50px;">
                <h3>Comments <small>{{ $post->comments()->count() }} total</small></h3>

                <table class="table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Comment</th>
                        <th width="70px"></th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($post->comments as $comment)
                        <tr>
                            <td>{{ $comment->name }}</td>
                            <td>{{ $comment->email }}</td>
                            <td>{{ $comment->comment }}</td>
                            <td>
                                <a href="{{ route('comments.edit', $comment->id) }}" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a href="{{ route('comments.delete', $comment->id) }}" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <label>Url:</label>
                    <p><a href="{{ route('blog.single', $post->slug) }}">{{ route('blog.single', $post->slug) }}</a></p>
                </dl>

                <dl class="dl-horizontal">
                    <label>Category:</label>
                    <p>{{ $post->category->name }}</p>
                </dl>

                <dl class="dl-horizontal">
                    <label>Created At:</label>
                    <p>{{ date('M j, Y h:ia', strtotime($post->created_at)) }}</p>
                </dl>

                <dl class="dl-horizontal">
                    <label>Last Updated:</label>
                    <p>{{ date('M j, Y h:ia', strtotime($post->updated_at)) }}</p>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        {!! Html::linkRoute('posts.edit', 'Edit', array($post->id), array('class' => 'btn btn-primary btn-block')) !!}
                    </div>
                    <div class="col-sm-6">
                        {!! Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'DELETE']) !!}

                        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) !!}

                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        {{ Html::linkRoute('posts.index', '<< See All Posts', array(), ['class' => 'btn btn-default btn-block btn-h1-spacing']) }}
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection